# pre commit hook config
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: trailing-whitespace
      stages: [pre-commit]
    - id: detect-private-key
      stages: [pre-commit]
    - id: check-added-large-files
      stages: [pre-commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    - id: ruff
      types_or: [ python, pyi ]
      stages: [pre-commit]
      args: [ --fix, --unsafe-fixes ]
    - id: ruff-format
      stages: [pre-commit]
      types_or: [ python, pyi ]

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.11
    hooks:
    - id: uv-lock
      stages: [pre-commit]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
    # Run the linter.
   # - id: ruff
   #   args: [ --fix, --unsafe-fixes]
    # Run the formatter.
    - id: ruff-format

# pre push needs install of podman & podman-compose
-   repo: local
    hooks:
    - id: run-unit-tests
      name: Run unit tests in container
      entry:  bash -c 'PYTEST=TRUE  podman-compose up --build --force-recreate --remove-orphans'
      language: system
      stages: [pre-push]
      verbose: true
